import { createClient } from '@mercurjs/client';

/**
 * `Routes` is a placeholder, not the generated route map.
 *
 * The panels in the backend repo pass the real thing, generated by `mercurjs codegen`
 * into `@acme/api/_generated`. This repository cannot: that file resolves roughly half
 * its routes through `@mercurjs/core`, a server framework that is deliberately not a
 * dependency here — the storefront is a separate deployment on React 19 precisely to
 * stay decoupled from the backend's tree.
 *
 * The consequence is that `sdk` gives no response types at all: every call resolves to
 * `{}`. Responses are therefore typed at the data layer instead, in `lib/data/*.ts`,
 * using the published `HttpTypes` (@medusajs/types) and `@mercurjs/types/http` — which
 * is also how Medusa's own Next.js starter does it. See `apiResponse` below.
 */
type Routes = Record<string, unknown>;

const MEDUSA_BACKEND_URL = process.env.MEDUSA_BACKEND_URL || 'http://localhost:9000';

/**
 * One endpoint. The client builds these from the route map; with a placeholder map it
 * cannot, so they are declared permissively here and the RESPONSE is typed at the call
 * site instead — see `apiResponse`.
 */
type Endpoint = {
  query: (input?: Record<string, unknown>) => Promise<unknown>;
  mutate: (input?: Record<string, unknown>) => Promise<unknown>;
  delete: (input?: Record<string, unknown>) => Promise<unknown>;
};

/**
 * A navigable client: any path resolves, every call returns `unknown`.
 *
 * Without this, `sdk.store` is `{}` and even `sdk.store.regions` is a type error — the
 * paths fail before any response typing can help. That accounted for most of the errors
 * this file's placeholder `Routes` was causing.
 *
 * The trade is explicit: PATHS are not verified (a typo reaches runtime, exactly as it
 * does today), while RESPONSES are typed, at one place per endpoint. Restoring path
 * checking means passing the generated route map — see the note on `Routes` above.
 */
type NavigableClient = Endpoint & { [segment: string]: NavigableClient };

export const sdk = createClient({
  baseUrl: MEDUSA_BACKEND_URL,
  fetchOptions: {
    headers: {
      'x-publishable-api-key': process.env.NEXT_PUBLIC_MEDUSA_PUBLISHABLE_KEY as string,
    },
  },
}) as NavigableClient;

/**
 * The single boundary where an untyped SDK response becomes a typed one.
 *
 * This is an assertion, not a validation — it does not check anything at runtime. It
 * exists so the assertion happens ONCE PER ENDPOINT, in the data layer, next to the
 * request that produced it, rather than being scattered as inline `as any` through the
 * components. If a response shape changes on the backend, the fix belongs at exactly
 * these call sites.
 */
export const apiResponse = <T>(promise: unknown): Promise<T> =>
  promise as Promise<T>;
